import { motion } from "framer-motion";
import { Camera, Timer, Brain, Shield, BarChart3, AlertTriangle } from "lucide-react";

const features = [
  { icon: Brain, title: "Dynamic Questions", desc: "20 unique MCQs generated by Gemini AI every round" },
  { icon: Camera, title: "Live Proctoring", desc: "Real-time webcam monitoring with face detection" },
  { icon: Timer, title: "Timed Assessment", desc: "15-minute countdown with auto-submission" },
  { icon: Shield, title: "Integrity Score", desc: "Cheat detection tracks tab switches & face events" },
  { icon: AlertTriangle, title: "Instant Alerts", desc: "Warnings for missing face or multiple faces" },
  { icon: BarChart3, title: "Detailed Report", desc: "Score, weak areas, and improvement suggestions" },
];

const FeaturesSection = () => {
  return (
    <section id="features" className="py-24 px-6 border-t border-border/30">
      <div className="container mx-auto">
        <div className="text-center mb-16">
          <h2 className="section-title">
            Built for <span className="text-primary">Serious</span> Preparation
          </h2>
          <p className="section-subtitle mt-4">
            Every feature designed to simulate a real interview environment
          </p>
        </div>

        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 15 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.05 }}
              className="glass-card p-6 hover:glow-border transition-all duration-300"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 mb-4">
                <f.icon className="h-5 w-5 text-primary" />
              </div>
              <h3 className="font-display text-lg font-semibold text-foreground">{f.title}</h3>
              <p className="text-sm text-muted-foreground mt-2">{f.desc}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesSection;
